name: Suggestion
description: Propose an improvement to the guides or templates
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Proposal
      description: What would you like to change and why?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Example
      description: Provide a before/after or short snippet if helpful.
  - type: checkboxes
    attributes:
      label: Scope
      options:
        - label: README Style Guide
        - label: Git Commit Style Guide
        - label: Comments & Documentation (JS/TS)
        - label: Templates
        - label: Examples
